export default interface Usuario {
    id: number,
    uuid: string,
    nombre: string,
    apellido1: string,
    apellido2: string,
    telefono: string,
    cedula: string | null,
    institucion: string | null,
    rfc: string,
    sexo: string,
    fecha_nacimiento: Date,
    tipo_usuario: string,
    servicio_id: number | null,
    unidad_id: number | null,
    estatus: boolean | number,
    email: string,
    username: string,
}